import 'dart:math';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:image_picker/image_picker.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() => runApp(const ThreeTrioApp());

class ThreeTrioApp extends StatelessWidget {
  const ThreeTrioApp({super.key});
  @override Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false, title: '3TRIO', theme: AppTheme.theme, home: const HomeShell());
}

class AppTheme {
  static ThemeData get theme => ThemeData(
    brightness: Brightness.dark, useMaterial3: true, scaffoldBackgroundColor: const Color(0xFF07080C),
    colorScheme: const ColorScheme.dark(primary: Color(0xFFE5485D), secondary: Color(0xFF8A6CFF), surface: Color(0xFF11131A)),
    textTheme: GoogleFonts.interTextTheme(ThemeData.dark().textTheme).apply(bodyColor: const Color(0xFFF4F2F3), displayColor: Colors.white),
    navigationBarTheme: NavigationBarThemeData(backgroundColor: const Color(0xFF090A0F), indicatorColor: const Color(0xFF2A141A), labelTextStyle: WidgetStatePropertyAll(TextStyle(fontSize: 11, fontWeight: FontWeight.w600)), height: 70),
    chipTheme: ChipThemeData(backgroundColor: const Color(0xFF171923), side: const BorderSide(color: Color(0xFF292C36)), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(22))),
  );
}

class HomeShell extends StatefulWidget { const HomeShell({super.key}); @override State<HomeShell> createState()=>_HomeShellState(); }
class _HomeShellState extends State<HomeShell> {
  int index=0;
  final pages=const [DiscoverPage(), FeedPage(), MapPage(), LikesPage(), MessagesPage()];
  final labels=['Discover','Feed','Map','Likes','Messages'];
  final icons=[Icons.explore_outlined,Icons.dynamic_feed_outlined,Icons.map_outlined,Icons.favorite_border,Icons.chat_bubble_outline];
  @override Widget build(BuildContext c)=>Scaffold(body: SafeArea(child: pages[index]), bottomNavigationBar: NavigationBar(selectedIndex:index,onDestinationSelected:(i)=>setState(()=>index=i),destinations:[for(var i=0;i<5;i++) NavigationDestination(icon:Icon(icons[i]),label:labels[i])]));
}

class DiscoverPage extends StatefulWidget { const DiscoverPage({super.key}); @override State<DiscoverPage> createState()=>_DiscoverState(); }
class _DiscoverState extends State<DiscoverPage> {
  int card=0; final profiles=const [
    ('Maya','28','Delhi · 8 km','She/Her','Open to exploring','Travel • Music • Rooftops','Looking for genuine chemistry, good conversation and people who are clear about what they want.'),
    ('Alex & Sam','31','Gurugram · 14 km','They/Them','Couple · Connections','Food • Parties • Fitness','Two verified people looking to meet interesting, respectful connections.'),
    ('Riya','30','Noida · 21 km','She/Her','Curious','Art • Coffee • Events','Slow conversations, real-world chemistry and new experiences.'),
  ];
  @override Widget build(BuildContext c){ final p=profiles[card%profiles.length]; return Column(children:[
    Padding(padding:const EdgeInsets.fromLTRB(18,10,14,8),child:Row(children:[const Expanded(child:Text('3TRIO',style:TextStyle(fontSize:25,fontWeight:FontWeight.w800,letterSpacing:1.4))),IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const SettingsPage())),icon:const Icon(Icons.tune_rounded))])),
    SizedBox(height:40,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:16),children:['Desires','Distance','Gender','Sexuality','Verified','Active'].map((x)=>Padding(padding:const EdgeInsets.only(right:8),child:ActionChip(label:Text(x),onPressed:()=>showModalBottomSheet(context:c,isScrollControlled:true,backgroundColor:const Color(0xFF11131A),builder:(_)=>const FilterSheet())))).toList())),
    Expanded(child:Padding(padding:const EdgeInsets.fromLTRB(14,8,14,10),child:Stack(children:[
      Container(decoration:BoxDecoration(borderRadius:BorderRadius.circular(30),gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Colors.grey.shade800,const Color(0xFF15151B)])),child:Column(children:[
        Expanded(flex:7,child:Stack(children:[Container(decoration:BoxDecoration(borderRadius:BorderRadius.circular(30),image:DecorationImage(image:NetworkImage('https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=1000'),fit:BoxFit.cover))),Positioned(left:18,top:18,child:const Row(children:[_Badge(icon:Icons.verified,label:'Photo verified'),SizedBox(width:6),_Badge(icon:Icons.mic,label:'Voice verified')])),Positioned(left:20,right:20,bottom:18,child:Text('${p.$1}, ${p.$2}',style:const TextStyle(fontSize:30,fontWeight:FontWeight.w800)))])),
        Expanded(flex:3,child:Padding(padding:const EdgeInsets.fromLTRB(20,12,20,8),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${p.$3}  •  ${p.$4}',style:const TextStyle(color:Colors.white70)),const SizedBox(height:7),Wrap(spacing:6,children:[_Pill(p.$5),_Pill(p.$6)]),const SizedBox(height:8),Expanded(child:Text(p.$7,maxLines:3,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white70,height:1.35)))])))
      ])),
      Positioned(left:20,right:20,bottom:10,child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[_RoundAction(icon:Icons.close_rounded,onTap:()=>setState(()=>card++)),_RoundAction(icon:Icons.bolt_rounded,active:true,onTap:()=>_toast(c,'Ping sent')), _RoundAction(icon:Icons.favorite_rounded,onTap:()=>_toast(c,'Like sent'))]))
    ]))),
  ]); }
}

class FeedPage extends StatefulWidget { const FeedPage({super.key}); @override State<FeedPage> createState()=>_FeedState(); }
class _FeedState extends State<FeedPage>{ int mode=0; @override Widget build(BuildContext c)=>Column(children:[_Header(title:'Feed',action:'Create',onAction:()=>showModalBottomSheet(context:c,isScrollControlled:true,backgroundColor:const Color(0xFF11131A),builder:(_)=>const CreatePostSheet())),
  SizedBox(height:45,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:16),children:['Stories','Text','Photo','Video'].asMap().entries.map((e)=>Padding(padding:const EdgeInsets.only(right:8),child:ChoiceChip(label:Text(e.value),selected:mode==e.key,onSelected:(_)=>setState(()=>mode=e.key)))).toList())),
  Expanded(child:ListView(padding:const EdgeInsets.fromLTRB(14,8,14,18),children:[const StoryStrip(),PostCard(name:'Maya',time:'12 min',verified:true,text:'Sunset rooftop plans tonight. Who is around?',tags:['Rooftop','Social'],image:'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=900'),PostCard(name:'Alex & Sam',time:'1 h',verified:true,text:'Weekend plans: food, music and good people.',tags:['Food','Music'],image:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=900')]))]);}

class StoryStrip extends StatelessWidget{const StoryStrip({super.key});@override Widget build(BuildContext c)=>SizedBox(height:100,child:ListView(scrollDirection:Axis.horizontal,children:[for(final n in ['You','Maya','Alex','Riya','Sam']) Padding(padding:const EdgeInsets.only(right:16),child:Column(children:[CircleAvatar(radius:30,backgroundColor:const Color(0xFF252733),child:Text(n[0],style:const TextStyle(fontWeight:FontWeight.w800))),const SizedBox(height:5),Text(n,style:const TextStyle(fontSize:11))]))]));}
class PostCard extends StatelessWidget{final String name,time,text,image;final bool verified;final List<String> tags;const PostCard({super.key,required this.name,required this.time,required this.text,required this.image,required this.tags,this.verified=false});@override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.only(bottom:16),decoration:BoxDecoration(color:const Color(0xFF101219),borderRadius:BorderRadius.circular(24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:16),leading:CircleAvatar(child:Text(name[0])),title:Row(children:[Text(name,style:const TextStyle(fontWeight:FontWeight.w700)),if(verified)const Padding(padding:EdgeInsets.only(left:5),child:Icon(Icons.verified,size:15,color:Color(0xFFE5485D)))]),subtitle:Text(time,style:const TextStyle(color:Colors.white54)),trailing:const Icon(Icons.more_horiz)),Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:Text(text,style:const TextStyle(fontSize:15,height:1.35))),const SizedBox(height:10),ClipRRect(borderRadius:BorderRadius.circular(18),child:Image.network(image,height:230,width:double.infinity,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(height:230,color:Colors.black26))),Padding(padding:const EdgeInsets.all(14),child:Row(children:[for(final t in tags)Padding(padding:const EdgeInsets.only(right:7),child:_Pill(t)),const Spacer(),const Icon(Icons.favorite_border),const SizedBox(width:18),const Icon(Icons.mode_comment_outlined)]))]));}

class MapPage extends StatefulWidget{const MapPage({super.key});@override State<MapPage> createState()=>_MapState();}
class _MapState extends State<MapPage>{int mode=0;@override Widget build(BuildContext c)=>Column(children:[Padding(padding:const EdgeInsets.fromLTRB(18,10,18,6),child:Row(children:[const Expanded(child:Text('Map',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800))),IconButton(onPressed:()=>_toast(c,'Map visibility settings'),icon:const Icon(Icons.my_location_outlined))])),SizedBox(height:42,child:Row(mainAxisAlignment:MainAxisAlignment.center,children:['People','Activities','Both'].asMap().entries.map((e)=>Padding(padding:const EdgeInsets.symmetric(horizontal:4),child:ChoiceChip(label:Text(e.value),selected:mode==e.key,onSelected:(_)=>setState(()=>mode=e.key))).toList())),Expanded(child:Stack(children:[Container(margin:const EdgeInsets.all(14),decoration:BoxDecoration(borderRadius:BorderRadius.circular(28),color:const Color(0xFF101923),gradient:const LinearGradient(colors:[Color(0xFF192332),Color(0xFF0C1118)])),child:CustomPaint(painter:MapPainter(),child:Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.location_on_rounded,size:48,color:Color(0xFFE5485D)),const SizedBox(height:8),Text(mode==1?'Activities nearby':'People nearby',style:const TextStyle(fontSize:20,fontWeight:FontWeight.w700)),const SizedBox(height:4),const Text('Approximate zones only',style:TextStyle(color:Colors.white54))])))),Positioned(left:28,right:28,bottom:30,child:Row(children:[Expanded(child:FilledButton.icon(onPressed:()=>showModalBottomSheet(context:c,isScrollControlled:true,backgroundColor:const Color(0xFF11131A),builder:(_)=>const CreateActivitySheet()),icon:const Icon(Icons.add),label:const Text('Create Activity'))),const SizedBox(width:10),IconButton.filled(onPressed:()=>_toast(c,'Your exact GPS is never displayed'),icon:const Icon(Icons.shield_outlined))]))]))]);}
class MapPainter extends CustomPainter{ @override void paint(Canvas c,Size s){final p=Paint()..color=Colors.white.withOpacity(.06)..strokeWidth=1;for(var x=0;x<s.width;x+=45)c.drawLine(Offset(x,0),Offset(x,s.height),p);for(var y=0;y<s.height;y+=45)c.drawLine(Offset(0,y),Offset(s.width,y),p);final q=Paint()..color=const Color(0xFFE5485D);for(final o in [Offset(s.width*.22,s.height*.25),Offset(s.width*.72,s.height*.34),Offset(s.width*.38,s.height*.68),Offset(s.width*.78,s.height*.72)])c.drawCircle(o,7,q);} @override bool shouldRepaint(covariant CustomPainter old)=>false;}

class LikesPage extends StatelessWidget{const LikesPage({super.key});@override Widget build(BuildContext c)=>Column(children:[_Header(title:'Likes',action:'Premium',onAction:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const PremiumPage()))),const SizedBox(height:10),Expanded(child:ListView(padding:const EdgeInsets.all(14),children:[const _LikeItem(name:'Maya',kind:'Liked you · 8 km',color:Color(0xFFE5485D)),const _LikeItem(name:'Alex & Sam',kind:'Pinged you · 14 km',color:Color(0xFF8A6CFF)),const _LikeItem(name:'Riya',kind:'Liked you · 21 km',color:Color(0xFFE5485D))]))]);}
class _LikeItem extends StatelessWidget{final String name,kind;final Color color;const _LikeItem({required this.name,required this.kind,required this.color});@override Widget build(BuildContext c)=>ListTile(contentPadding:const EdgeInsets.symmetric(vertical:6),leading:CircleAvatar(radius:28,backgroundColor:color.withOpacity(.18),child:Text(name[0],style:TextStyle(color:color,fontWeight:FontWeight.w800))),title:Text(name,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(kind),trailing:IconButton(onPressed:()=>_toast(c,'Connection opened'),icon:Icon(Icons.favorite,color:color)));}

class MessagesPage extends StatelessWidget{const MessagesPage({super.key});@override Widget build(BuildContext c)=>Column(children:[_Header(title:'Messages',action:'New',onAction:()=>_toast(c,'Start a private conversation')),Expanded(child:ListView(padding:const EdgeInsets.all(12),children:[ChatTile(name:'Maya',text:'Are you around tonight?',time:'20:14'),ChatTile(name:'Alex & Sam',text:'That activity looks great',time:'19:40'),ChatTile(name:'Riya',text:'Seen your profile ✨',time:'18:05')]))]);}
class ChatTile extends StatelessWidget{final String name,text,time;const ChatTile({super.key,required this.name,required this.text,required this.time});@override Widget build(BuildContext c)=>ListTile(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ChatPage(name:name)),contentPadding:const EdgeInsets.symmetric(horizontal:8,vertical:5),leading:CircleAvatar(radius:28,child:Text(name[0])),title:Text(name,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(text),trailing:Text(time,style:const TextStyle(color:Colors.white38)));}

class ChatPage extends StatefulWidget{final String name;const ChatPage({super.key,required this.name});@override State<ChatPage> createState()=>_ChatState();}
class _ChatState extends State<ChatPage>{final ctrl=TextEditingController();bool oneView=false;final msgs=<String>['Hey 👋','How is your evening going?'];@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Row(children:[CircleAvatar(radius:17,child:Text(widget.name[0])),const SizedBox(width:10),Text(widget.name)]),actions:[IconButton(onPressed:()=>_toast(c,'Audio call'),icon:const Icon(Icons.call_outlined)),IconButton(onPressed:()=>_toast(c,'Video call'),icon:const Icon(Icons.videocam_outlined))]),body:Column(children:[const Padding(padding:EdgeInsets.all(8),child:Text('🛡 Secure Chat · Protected media',style:TextStyle(color:Colors.greenAccent,fontSize:12))),Expanded(child:ListView(padding:const EdgeInsets.all(16),children:[for(final m in msgs)Align(alignment:Alignment.centerRight,child:Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.symmetric(horizontal:15,vertical:11),decoration:BoxDecoration(color:const Color(0xFF262936),borderRadius:BorderRadius.circular(18)),child:Text(m)))])),SafeArea(child:Row(children:[IconButton(onPressed:()=>_pick(c),icon:const Icon(Icons.photo_outlined)),IconButton(onPressed:()=>setState(()=>oneView=!oneView),icon:Icon(oneView?Icons.timer:Icons.timer_outlined,color:oneView?const Color(0xFFE5485D):null)),Expanded(child:TextField(controller:ctrl,decoration:const InputDecoration(hintText:'Message…',border:InputBorder.none))),IconButton(onPressed:(){if(ctrl.text.trim().isNotEmpty){setState(()=>msgs.add(ctrl.text.trim()));ctrl.clear();}},icon:const Icon(Icons.send_rounded))]))]));}
Future<void>_pick(BuildContext c)async{final x=await ImagePicker().pickImage(source:ImageSource.gallery);if(x!=null)_toast(c,oneView?'One-view media selected':'Media selected');}}

class SettingsPage extends StatefulWidget{const SettingsPage({super.key});@override State<SettingsPage> createState()=>_SettingsState();}
class _SettingsState extends State<SettingsPage>{bool incognito=false,map=true,haptics=true,km=true;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Settings')),body:ListView(children:[const Section('Account'),SettingRow(icon:Icons.person_outline,title:'Edit Profile',onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ProfilePage()))),SettingRow(icon:Icons.verified_outlined,title:'Verification',subtitle:'Photo · Government ID · Voice',onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const VerificationPage()))),const Section('Privacy'),SwitchListTile(value:incognito,onChanged:(v)=>setState(()=>incognito=v),title:const Text('Incognito'),secondary:const Icon(Icons.visibility_off_outlined)),SwitchListTile(value:map,onChanged:(v)=>setState(()=>map=v),title:const Text('Map visibility'),secondary:const Icon(Icons.map_outlined)),SettingRow(icon:Icons.photo_library_outlined,title:'Private Photos',subtitle:'Never shown in Discover, Feed or Map',onTap:()=>_toast(c,'Private photo controls')),const Section('Preferences'),SwitchListTile(value:km,onChanged:(v)=>setState(()=>km=v),title:Text('Distance: ${km?'KM':'Miles'}'),secondary:const Icon(Icons.straighten)),SwitchListTile(value:haptics,onChanged:(v)=>setState(()=>haptics=v),title:const Text('Haptic feedback'),secondary:const Icon(Icons.vibration)),const Section('Safety'),SettingRow(icon:Icons.block_outlined,title:'Blocked users',onTap:()=>_toast(c,'Blocked users')),SettingRow(icon:Icons.flag_outlined,title:'Report & Safety',onTap:()=>_toast(c,'Safety centre')),const Section('Account'),SettingRow(icon:Icons.pause_circle_outline,title:'Pause account',onTap:()=>_toast(c,'Account paused')),SettingRow(icon:Icons.delete_outline,title:'Delete account',onTap:()=>_toast(c,'Deletion requires confirmation'))]));}}

class ProfilePage extends StatelessWidget{const ProfilePage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Edit Profile'),actions:[TextButton(onPressed:()=>_toast(c,'Saved'),child:const Text('Save'))]),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Photos  3/5',style:TextStyle(fontSize:20,fontWeight:FontWeight.w700)),const SizedBox(height:10),Wrap(spacing:10,runSpacing:10,children:[for(var i=0;i<5;i++)Container(width:100,height:125,decoration:BoxDecoration(color:const Color(0xFF171923),borderRadius:BorderRadius.circular(18)),child:Center(child:Icon(i<3?Icons.person:Icons.add_a_photo_outlined,color:i<3?Colors.white:Colors.white38,size:30)))),const SizedBox(height:25),const TextField(decoration:InputDecoration(labelText:'Bio',hintText:'Tell people what you are looking for…')),const SizedBox(height:15),const TextField(decoration:InputDecoration(labelText:'What are you looking for?')),const SizedBox(height:15),const Text('Desires',style:TextStyle(fontWeight:FontWeight.w700)),const Wrap(spacing:7,children:[_Pill('Open-minded'),_Pill('Dating'),_Pill('Connections'),_Pill('Curious')]),const SizedBox(height:20),const Text('Interests',style:TextStyle(fontWeight:FontWeight.w700)),const Wrap(spacing:7,children:[_Pill('Travel'),_Pill('Music'),_Pill('Fitness'),_Pill('Food'),_Pill('Events')]),const SizedBox(height:20),SettingRow(icon:Icons.lock_outline,title:'Hidden Bio',subtitle:'Reveal only under your chosen condition',onTap:()=>_toast(c,'Hidden Bio settings')),SettingRow(icon:Icons.visibility_outlined,title:'Fantasy',subtitle:'Public · Connections · Private',onTap:()=>_toast(c,'Fantasy privacy settings'))]));}

class VerificationPage extends StatelessWidget{const VerificationPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Verification')),body:ListView(padding:const EdgeInsets.all(18),children:[const Text('Verification is required for every member.',style:TextStyle(fontSize:17,height:1.4)),const SizedBox(height:18),VerifyTile(icon:Icons.camera_alt_outlined,title:'Photo verification',subtitle:'Live selfie check',status:'Required'),VerifyTile(icon:Icons.badge_outlined,title:'Government ID',subtitle:'Private — never public',status:'Required'),VerifyTile(icon:Icons.mic_none_outlined,title:'Voice verification',subtitle:'Record inside 3TRIO',status:'Required'),const SizedBox(height:15),const Text('Each badge is separate. Verification never means a member is “100% safe”.',style:TextStyle(color:Colors.white54))]));}
class VerifyTile extends StatelessWidget{final IconData icon;final String title,subtitle,status;const VerifyTile({super.key,required this.icon,required this.title,required this.subtitle,required this.status});@override Widget build(BuildContext c)=>Card(color:const Color(0xFF11131A),child:ListTile(leading:Icon(icon),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(subtitle),trailing:Chip(label:Text(status))));}

class PremiumPage extends StatelessWidget{const PremiumPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('3TRIO Premium')),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('Go further',style:TextStyle(fontSize:32,fontWeight:FontWeight.w800)),const SizedBox(height:8),const Text('Unlimited likes + see who liked you.',style:TextStyle(color:Colors.white60)),const SizedBox(height:22),for(final x in [('Monthly','₹500'),('6 months','₹2,500'),('Yearly','₹4,000')])Card(color:const Color(0xFF14161F),child:ListTile(title:Text(x.$1,style:const TextStyle(fontWeight:FontWeight.w700)),trailing:Text(x.$2,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800)),onTap:()=>_toast(c,'Checkout will use real store billing when configured')))]));}

class FilterSheet extends StatelessWidget{const FilterSheet({super.key});@override Widget build(BuildContext c)=>Padding(padding:EdgeInsets.only(bottom:MediaQuery.of(c).viewInsets.bottom),child:SingleChildScrollView(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Discover filters',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800)),const SizedBox(height:20),const Text('Age'),RangeSlider(values:const RangeValues(21,45),min:18,max:70,onChanged:(_){ }),const Text('Distance'),const Slider(value:25,min:1,max:100,onChanged:(_){ }),const Text('Gender'),const Wrap(spacing:7,children:[_Pill('Women'),_Pill('Men'),_Pill('Non-binary'),_Pill('Couples')]),const SizedBox(height:12),const Text('Desires & Interests'),const Wrap(spacing:7,children:[_Pill('Dating'),_Pill('Open-minded'),_Pill('Travel'),_Pill('Music'),_Pill('Events')]),const SizedBox(height:20),SwitchListTile(value:true,onChanged:(_){},title:const Text('Verified only')),SwitchListTile(value:true,onChanged:(_){},title:const Text('Recently active')),FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Apply filters'))])));}

class CreatePostSheet extends StatelessWidget{const CreatePostSheet({super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(20),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Create post',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800)),const SizedBox(height:15),const TextField(maxLines:4,decoration:InputDecoration(hintText:'Share something with your connections…')),const SizedBox(height:15),Row(children:[OutlinedButton.icon(onPressed:()=>_toast(c,'Photo picker'),icon:const Icon(Icons.photo),label:const Text('Photo')),const SizedBox(width:8),OutlinedButton.icon(onPressed:()=>_toast(c,'Video picker'),icon:const Icon(Icons.videocam),label:const Text('Video')),const Spacer(),FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Post'))]),const SizedBox(height:10)]));}
class CreateActivitySheet extends StatelessWidget{const CreateActivitySheet({super.key});@override Widget build(BuildContext c)=>Padding(padding:EdgeInsets.only(left:20,right:20,top:20,bottom:MediaQuery.of(c).viewInsets.bottom+20),child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Create Activity',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800)),const SizedBox(height:15),const TextField(decoration:InputDecoration(labelText:'Title')),const TextField(decoration:InputDecoration(labelText:'Description')),const TextField(decoration:InputDecoration(labelText:'Category')),const TextField(decoration:InputDecoration(labelText:'General location')),const TextField(decoration:InputDecoration(labelText:'Date & start time')),const TextField(decoration:InputDecoration(labelText:'Max participants')),const SizedBox(height:18),FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Publish activity'))])));}

class Section extends StatelessWidget{final String text;const Section(this.text,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.fromLTRB(20,24,20,6),child:Text(text.toUpperCase(),style:const TextStyle(fontSize:12,color:Colors.white54,fontWeight:FontWeight.w800,letterSpacing:1.2)));}
class SettingRow extends StatelessWidget{final IconData icon;final String title;final String? subtitle;final VoidCallback onTap;const SettingRow({super.key,required this.icon,required this.title,this.subtitle,required this.onTap});@override Widget build(BuildContext c)=>ListTile(onTap:onTap,leading:Icon(icon),title:Text(title),subtitle:subtitle==null?null:Text(subtitle!),trailing:const Icon(Icons.chevron_right));}
class _Header extends StatelessWidget{final String title,action;final VoidCallback onAction;const _Header({required this.title,required this.action,required this.onAction});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.fromLTRB(18,10,12,6),child:Row(children:[Expanded(child:Text(title,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w800))),TextButton(onPressed:onAction,child:Text(action))]));}
class _Badge extends StatelessWidget{final IconData icon;final String label;const _Badge({required this.icon,required this.label});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:6),decoration:BoxDecoration(color:Colors.black54,borderRadius:BorderRadius.circular(20)),child:Row(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:13),const SizedBox(width:4),Text(label,style:const TextStyle(fontSize:11))]));}
class _Pill extends StatelessWidget{final String text;const _Pill(this.text);@override Widget build(BuildContext c)=>Chip(label:Text(text,style:const TextStyle(fontSize:11)));}
class _RoundAction extends StatelessWidget{final IconData icon;final bool active;final VoidCallback onTap;const _RoundAction({required this.icon,required this.onTap,this.active=false});@override Widget build(BuildContext c)=>GestureDetector(onTap:onTap,child:Container(width:56,height:56,decoration:BoxDecoration(shape:BoxShape.circle,color:active?const Color(0xFF342044):const Color(0xFF181A22),border:Border.all(color:active?const Color(0xFF8A6CFF):Colors.white12)),child:Icon(icon,color:active?const Color(0xFFBBAAFF):Colors.white,size:25)));}
class _Stub extends StatelessWidget{final String title;const _Stub(this.title);@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(title)),body:Center(child:Text(title)));}
class CallPage extends StatelessWidget{final bool video;const CallPage({super.key,this.video=false});@override Widget build(BuildContext c)=>Scaffold(backgroundColor:Colors.black,body:Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(video?Icons.videocam:Icons.call,size:60),const SizedBox(height:15),const Text('Real-time call service ready for WebRTC integration'),const SizedBox(height:20),FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('End call'))])));}
void _toast(BuildContext c,String s){ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(s),behavior:SnackBarBehavior.floating));}
