import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const TrioApp());
}

class TrioApp extends StatelessWidget {
  const TrioApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: '3TRIO',
    theme: ThemeData(useMaterial3: true, colorSchemeSeed: const Color(0xFFE83E72), scaffoldBackgroundColor: const Color(0xFFF8F7FA)),
    darkTheme: ThemeData(useMaterial3: true, brightness: Brightness.dark, colorSchemeSeed: const Color(0xFFFF3F78), scaffoldBackgroundColor: const Color(0xFF09090D)),
    home: const SplashScreen(),
  );
}

class TrioProfile {
  final String name, age, gender, bio;
  final List<String> interests, photos;
  final bool verified, premium;
  const TrioProfile({required this.name, required this.age, required this.gender, required this.bio, this.interests=const [], this.photos=const [], this.verified=false, this.premium=false});
}

final demoProfiles = <TrioProfile>[
  const TrioProfile(name:'Alex & Sam',age:'29 · 31',gender:'Couple',bio:'Open-minded, respectful and here for genuine connections.',interests:['ENM','Travel','Music'],verified:true,photos:['https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=900']),
  const TrioProfile(name:'Maya',age:'28',gender:'Woman',bio:'Good conversation, travel and new experiences.',interests:['Travel','Fitness','Music'],verified:true,photos:['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=900']),
  const TrioProfile(name:'Jordan',age:'30',gender:'Man',bio:'Looking for genuine connections and good conversation.',interests:['Music','Fitness'],photos:['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900']),
  const TrioProfile(name:'Taylor',age:'27',gender:'Woman',bio:'Travel, music and respectful connections.',interests:['Travel','Music'],verified:true,photos:['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=900']),
];

class SplashScreen extends StatefulWidget { const SplashScreen({super.key}); @override State<SplashScreen> createState()=>_SplashState(); }
class _SplashState extends State<SplashScreen>{
 @override void initState(){super.initState(); Future.delayed(const Duration(milliseconds:900),(){if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const AgeGate()));});}
 @override Widget build(BuildContext c)=>Scaffold(body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Text('3TRIO',style:TextStyle(fontSize:48,fontWeight:FontWeight.w900,letterSpacing:5,color:Theme.of(c).colorScheme.primary)),const SizedBox(height:8),const Text('Meet openly. Connect intentionally.')])));}

class AgeGate extends StatelessWidget { const AgeGate({super.key}); @override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text('3TRIO',style:TextStyle(fontSize:44,fontWeight:FontWeight.w900,color:Theme.of(c).colorScheme.primary)),const SizedBox(height:14),const Text('A private social discovery space for adults.',textAlign:TextAlign.center,style:TextStyle(fontSize:18)),const SizedBox(height:18),const Chip(label:Text('18+ adults only')),const SizedBox(height:28),SizedBox(width:double.infinity,height:54,child:FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const LoginScreen())),child:const Text('I am 18 or older')))]))));}}

class LoginScreen extends StatelessWidget { const LoginScreen({super.key}); @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Welcome to 3TRIO')),body:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[
 _login(c,'Continue with Google',Icons.g_mobiledata),_login(c,'Continue with Apple',Icons.apple),_login(c,'Continue with phone',Icons.phone,phone:true),
 const SizedBox(height:18),const Text('Verification is required before discovery.',textAlign:TextAlign.center,style:TextStyle(color:Colors.grey))
 ]));}
 Widget _login(BuildContext c,String text,IconData icon,{bool phone=false})=>Padding(padding:const EdgeInsets.only(bottom:12),child:SizedBox(width:double.infinity,height:54,child:OutlinedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>phone?const PhoneLoginScreen():const OnboardingScreen())),icon:Icon(icon),label:Text(text))));}

class PhoneLoginScreen extends StatefulWidget { const PhoneLoginScreen({super.key}); @override State<PhoneLoginScreen> createState()=>_PhoneState(); }
class _PhoneState extends State<PhoneLoginScreen>{final phone=TextEditingController(); final otp=TextEditingController(); bool sent=false;
 Widget field(TextEditingController c,String label,{TextInputType? type})=>TextField(controller:c,keyboardType:type,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder()));
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Phone verification')),body:Padding(padding:const EdgeInsets.all(24),child:Column(children:[field(phone,'Phone number',type:TextInputType.phone),const SizedBox(height:14),if(sent)field(otp,'6 digit OTP',type:TextInputType.number),const SizedBox(height:16),SizedBox(width:double.infinity,child:FilledButton(onPressed:(){if(!sent){setState(()=>sent=true);ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Demo OTP sent')));}else Navigator.push(c,MaterialPageRoute(builder:(_)=>const OnboardingScreen()));},child:Text(sent?'Verify OTP':'Send OTP')))]));}}

class OnboardingScreen extends StatefulWidget { const OnboardingScreen({super.key}); @override State<OnboardingScreen> createState()=>_OnboardState(); }
class _OnboardState extends State<OnboardingScreen>{int step=0;String name='',age='',gender='';Set<String> interests={};int photos=0;String verification='';
final all=['Open Relationship','Ethical Non-Monogamy','Polyamory','Swinging','Roleplay','BDSM','Casual Fun','Threesomes','Group Play','Kink Exploration','Travel','Music','Fitness'];
bool get can=>step==0?name.trim().isNotEmpty&&int.tryParse(age)!=null:step==1?gender.isNotEmpty:step==2?interests.isNotEmpty:step==3?photos>=2:verification.isNotEmpty;
void next(){if(!can)return;if(step<4)setState(()=>step++);else Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>HomeScreen(profile:TrioProfile(name:name,age:age,gender:gender,bio:'New 3TRIO member',interests:interests.toList(),verified:true))));}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(leading:step>0?IconButton(onPressed:()=>setState(()=>step--),icon:const Icon(Icons.arrow_back)):null,title:Text('Set up your profile · ${step+1}/5')),body:Padding(padding:const EdgeInsets.all(22),child:Column(children:[LinearProgressIndicator(value:(step+1)/5),const SizedBox(height:25),Expanded(child:SingleChildScrollView(child:body())),const SizedBox(height:12),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:can?next:null,child:Text(step==4?'Create profile':'Next')))])));
Widget body(){if(step==0)return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text("What's your name?",style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:16),TextField(onChanged:(v)=>name=v,decoration:const InputDecoration(labelText:'First name',border:OutlineInputBorder())),const SizedBox(height:25),const Text('How old are you?',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:16),TextField(onChanged:(v)=>age=v,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Age',border:OutlineInputBorder()))]);
if(step==1)return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('I am a...',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:16),...['Man','Woman','Non-binary','Couple'].map((x)=>Padding(padding:const EdgeInsets.only(bottom:10),child: OutlinedButton(onPressed:()=>setState(()=>gender=x),style:OutlinedButton.styleFrom(minimumSize:const Size.fromHeight(52),side:BorderSide(width:gender==x?2:1,color:gender==x?Theme.of(context).colorScheme.primary:Colors.grey)),child:Text(x))))]);
if(step==2)return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('What are you looking for?',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const Text('Pick up to 5',style:TextStyle(color:Colors.grey)),const SizedBox(height:16),Wrap(spacing:8,runSpacing:8,children:all.map((x)=>FilterChip(label:Text(x),selected:interests.contains(x),onSelected:(v){if(v&&interests.length<5)setState(()=>interests.add(x));else if(!v)setState(()=>interests.remove(x));})).toList())]);
if(step==3)return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Add your photos',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('At least 2 photos, maximum 5.'),const SizedBox(height:20),Wrap(spacing:10,children:List.generate(5,(i)=>Container(width:58,height:82,decoration:BoxDecoration(color:Colors.grey.shade200,borderRadius:BorderRadius.circular(12)),child:Icon(i<photos?Icons.check_circle:Icons.add_a_photo)))),const SizedBox(height:20),OutlinedButton.icon(onPressed:()async{final p=await ImagePicker().pickImage(source:ImageSource.gallery);if(p!=null&&photos<5)setState(()=>photos++);},icon:const Icon(Icons.photo_library),label:const Text('Choose photo'))]);
return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Verification',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('Choose at least one verification method.'),const SizedBox(height:15),...['Photo verification','Government ID','Voice verification'].map((x)=>Card(child:ListTile(leading:const Icon(Icons.verified_user),title:Text(x),trailing:verification==x?const Icon(Icons.check_circle):TextButton(onPressed:()=>setState(()=>verification=x),child:const Text('Start'))))]);}
}

class HomeScreen extends StatefulWidget{final TrioProfile profile;const HomeScreen({super.key,required this.profile});@override State<HomeScreen> createState()=>_HomeState();}
class _HomeState extends State<HomeScreen>{int tab=0;final pages=<Widget>[const DiscoverScreen(),const FeedScreen(),const MapScreen(),const LikesScreen(),const MessagesScreen()];
@override Widget build(BuildContext c)=>Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.explore_outlined),selectedIcon:Icon(Icons.explore),label:'Discover'),NavigationDestination(icon:Icon(Icons.dynamic_feed_outlined),selectedIcon:Icon(Icons.dynamic_feed),label:'Feed'),NavigationDestination(icon:Icon(Icons.map_outlined),selectedIcon:Icon(Icons.map),label:'Map'),NavigationDestination(icon:Icon(Icons.favorite_border),selectedIcon:Icon(Icons.favorite),label:'Likes'),NavigationDestination(icon:Icon(Icons.chat_bubble_outline),selectedIcon:Icon(Icons.chat_bubble),label:'Chat')]));}}

class DiscoverScreen extends StatelessWidget{const DiscoverScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Discover'),actions:[IconButton(onPressed:()=>showModalBottomSheet(context:c,builder:(_)=>const FilterSheet()),icon:const Icon(Icons.tune)),IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const SettingsScreen())),icon:const Icon(Icons.settings_outlined))]),body:GridView.builder(padding:const EdgeInsets.all(12),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:10,mainAxisSpacing:10,childAspectRatio:.67),itemCount:demoProfiles.length,itemBuilder:(_,i){final p=demoProfiles[i];return GestureDetector(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ProfileDetailScreen(profile:p))),child:ClipRRect(borderRadius:BorderRadius.circular(18),child:Stack(fit:StackFit.expand,children:[Image.network(p.photos.first,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(color:Colors.grey,child:const Icon(Icons.person,size:60))),Align(alignment:Alignment.bottomCenter,child:Container(width:double.infinity,padding:const EdgeInsets.all(10),decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Colors.transparent,Colors.black87])),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${p.name} ${p.verified?'✓':''}',style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold,fontSize:16)),Text('${p.age} · ${p.gender}',style:const TextStyle(color:Colors.white70,fontSize:12)),Wrap(children:p.interests.take(2).map((x)=>Padding(padding:const EdgeInsets.only(right:4),child:Chip(label:Text(x),labelStyle:const TextStyle(fontSize:9),visualDensity:VisualDensity.compact))).toList())]))])));}});}

class ProfileDetailScreen extends StatelessWidget{final TrioProfile profile;const ProfileDetailScreen({super.key,required this.profile});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(profile.name)),body:ListView(children:[Image.network(profile.photos.first,height:430,fit:BoxFit.cover),Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${profile.name}  ${profile.verified?'✓':''}',style:const TextStyle(fontSize:26,fontWeight:FontWeight.bold)),Text('${profile.age} · ${profile.gender}',style:const TextStyle(color:Colors.grey)),const SizedBox(height:12),Text(profile.bio),const SizedBox(height:15),Wrap(spacing:7,children:profile.interests.map((x)=>Chip(label:Text(x))).toList()),const SizedBox(height:18),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>Navigator.pop(c),child:const Text('Pass'))),const SizedBox(width:10),Expanded(child:FilledButton(onPressed:()=>ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Like sent'))),child:const Text('♥ Like')))])]))]));}

class FeedScreen extends StatelessWidget{const FeedScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Community Feed'),actions:[IconButton(onPressed:()=>_info(c,'Create post','Post composer is ready for media/text integration.'),icon:const Icon(Icons.add))]),body:ListView(padding:const EdgeInsets.all(12),children:[PostCard(name:'3TRIO Community',text:'Meet openly. Connect intentionally. Keep it respectful and consensual.',image:'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=900'),PostCard(name:'Jordan',text:'Looking for genuine connections and good conversation.',image:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=900') ]));}}

class PostCard extends StatefulWidget{final String name,text,image;const PostCard({super.key,required this.name,required this.text,required this.image});@override State<PostCard> createState()=>_PostState();}
class _PostState extends State<PostCard>{bool liked=false;int comments=0;@override Widget build(BuildContext c)=>Card(clipBehavior:Clip.antiAlias,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(widget.name),subtitle:const Text('Today')),Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:Text(widget.text)),const SizedBox(height:10),Image.network(widget.image,height:260,width:double.infinity,fit:BoxFit.cover),Row(children:[IconButton(onPressed:()=>setState(()=>liked=!liked),icon:Icon(liked?Icons.favorite:Icons.favorite_border,color:liked?Colors.red:null)),IconButton(onPressed:()=>setState(()=>comments++),icon:const Icon(Icons.comment_outlined)),IconButton(onPressed:()=>_info(c,'Share','Share action selected'),icon:const Icon(Icons.share_outlined)),if(comments>0)Text('$comments')]) ]));}

class MapScreen extends StatelessWidget{const MapScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Nearby Map'),actions:[IconButton(onPressed:()=>_info(c,'Activity','Create an activity or social meetup.'),icon:const Icon(Icons.add_location_alt_outlined))]),body:Padding(padding:const EdgeInsets.all(12),child:Column(children:[const Text('Approximate locations only · exact GPS is never exposed.',textAlign:TextAlign.center),const SizedBox(height:12),Expanded(child:Container(decoration:BoxDecoration(borderRadius:BorderRadius.circular(24),gradient:const LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Color(0xFFE5EAF2),Color(0xFFC9D3E0)])),child:Stack(children:[const Center(child:Icon(Icons.map,size:120,color:Colors.blueGrey)),_pin(c,'Alex & Sam',.15,.25),_pin(c,'Maya',.62,.43),_pin(c,'Jordan',.35,.68)]))) ]));}
Widget _pin(BuildContext c,String s,double x,double y)=>Positioned(left:MediaQuery.of(c).size.width*x,top:MediaQuery.of(c).size.height*y*.55,child:Chip(avatar:const Icon(Icons.person,size:16),label:Text(s)));}

class LikesScreen extends StatelessWidget{const LikesScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Likes & Pings')),body:ListView(padding:const EdgeInsets.all(12),children:[const Card(child:ListTile(leading:Icon(Icons.favorite,color:Colors.red),title:Text('Someone nearby liked you'),subtitle:Text('Premium reveals who liked you.'))),const Card(child:ListTile(leading:Icon(Icons.bolt),title:Text('Sam sent a Ping'),subtitle:Text('Respond to connect.'))),Card(child:ListTile(leading:const Icon(Icons.workspace_premium),title:const Text('3TRIO Premium'),subtitle:const Text('Unlimited likes · premium filters'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const PremiumScreen()))) ]));}}

class MessagesScreen extends StatelessWidget{const MessagesScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Messages')),body:ListView(children:[ListTile(leading:const CircleAvatar(child:Icon(Icons.people)),title:const Text('Alex & Sam'),subtitle:const Text('Protected chat'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ChatScreen()))),const ListTile(leading:CircleAvatar(child:Icon(Icons.groups)),title:Text('Rooftop Social'),subtitle:Text('Activity chat · 5 going'))]));}

class ChatScreen extends StatefulWidget{const ChatScreen({super.key});@override State<ChatScreen> createState()=>_ChatState();}
class _ChatState extends State<ChatScreen>{final ctl=TextEditingController();final msgs=['Hey 👋','Hi, nice to meet you.'];@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Protected Chat'),actions:[IconButton(onPressed:()=>_info(c,'Audio call','Audio call integration point'),icon:const Icon(Icons.call_outlined)),IconButton(onPressed:()=>_info(c,'Video call','Video call integration point'),icon:const Icon(Icons.videocam_outlined))]),body:Column(children:[Expanded(child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:msgs.length,itemBuilder:(_,i)=>Align(alignment:i%2==0?Alignment.centerLeft:Alignment.centerRight,child:Container(margin:const EdgeInsets.only(bottom:8),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:i%2==0?Colors.grey.shade200:Theme.of(c).colorScheme.primary,borderRadius:BorderRadius.circular(16)),child:Text(msgs[i],style:TextStyle(color:i%2==0?null:Colors.white))))),),SafeArea(child:Row(children:[Expanded(child:TextField(controller:ctl,decoration:const InputDecoration(hintText:'Message…'))),IconButton(onPressed:(){if(ctl.text.trim().isNotEmpty)setState((){msgs.add(ctl.text.trim());ctl.clear();});},icon:const Icon(Icons.send))]))]));}

class PremiumScreen extends StatelessWidget{const PremiumScreen({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('3TRIO Premium')),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('Premium',style:TextStyle(fontSize:34,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Unlimited likes · See who liked you · Premium filters · more discovery controls'),const SizedBox(height:20),...['Monthly · ₹500','6 months · ₹2,500','Yearly · ₹4,000'].map((x)=>Card(child:ListTile(title:Text(x),trailing:FilledButton(onPressed:()=>_info(c,'Selected',x),child:const Text('Choose'))))) ]));}

class SettingsScreen extends StatefulWidget{const SettingsScreen({super.key});@override State<SettingsScreen> createState()=>_SettingsState();}
class _SettingsState extends State<SettingsScreen>{bool incognito=true,map=true,notifications=true,dark=false;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Settings')),body:ListView(children:[SwitchListTile(value:incognito,onChanged:(v)=>setState(()=>incognito=v),title:const Text('Incognito'),subtitle:const Text('Hide your profile from discovery')),SwitchListTile(value:map,onChanged:(v)=>setState(()=>map=v),title:const Text('Map visibility')),SwitchListTile(value:notifications,onChanged:(v)=>setState(()=>notifications=v),title:const Text('Notifications')),const Divider(),ListTile(leading:const Icon(Icons.verified_user),title:const Text('Verification'),onTap:()=>_info(c,'Verification','Photo, ID and voice verification flows')),const ListTile(title:Text('Privacy & Safety'),subtitle:Text('Blocked users, reporting and safety controls')),const ListTile(title:Text('Distance'),subtitle:Text('Kilometres')),ListTile(title:const Text('Premium'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const PremiumScreen()))),const ListTile(title:Text('Delete account'),textColor:Colors.red)]));}

class FilterSheet extends StatefulWidget{const FilterSheet({super.key});@override State<FilterSheet> createState()=>_FilterState();}
class _FilterState extends State<FilterSheet>{double distance=50;RangeValues age=const RangeValues(18,60);@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(22),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Discovery filters',style:TextStyle(fontSize:25,fontWeight:FontWeight.bold)),const SizedBox(height:15),Text('Age: ${age.start.round()} – ${age.end.round()}'),RangeSlider(values:age,min:18,max:80,onChanged:(v)=>setState(()=>age=v)),Text('Distance: ${distance.round()} km'),Slider(value:distance,min:1,max:100,onChanged:(v)=>setState(()=>distance=v)),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Apply filters')))]));}

void _info(BuildContext c,String title,String message)=>showModalBottomSheet(context:c,builder:(_)=>SafeArea(child:Padding(padding:const EdgeInsets.all(22),child:Column(mainAxisSize:MainAxisSize.min,children:[Text(title,style:const TextStyle(fontSize:23,fontWeight:FontWeight.bold)),const SizedBox(height:10),Text(message,textAlign:TextAlign.center),const SizedBox(height:18),FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Close'))]))));
