import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:geolocator/geolocator.dart';
import 'package:image_picker/image_picker.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:latlong2/latlong.dart';
import 'services/firestore_service.dart';

const restoredPrimary = Color(0xFFFF3B5C);
const lookingForOptions = ['Women','Men','Couples (FM)','Couples (FF)','Couples (MM)','Trans Women','Trans Men','Non-binary','Single Women','Single Men','Friends','Dates','New Experiences','Open Relationship','Ethical Non-Monogamy','Polyamory','Swinging','Threesomes','Group Play','Casual Fun','Long-term Connection','Travel Partners'];
const desireOptions = ['Open Relationship','Ethical Non-Monogamy','Polyamory','Swinging','Threesomes','Couples','Group Play','Casual Fun','Dating','Friends','Travel','Music','Fitness','Roleplay','BDSM','Kink Exploration','Dominance / Submission','New Experiences','Good Conversation'];

class RestoredStartScreen extends StatefulWidget{const RestoredStartScreen({super.key});@override State<RestoredStartScreen>createState()=>_StartState();}
class _StartState extends State<RestoredStartScreen>{
 int step=0,photos=0;String gender='',orientation='',name='',age='',bio='';final looking=<String>{};final desires=<String>{};
 bool get ok=>step==0?gender.isNotEmpty:step==1?name.isNotEmpty&&int.tryParse(age)!=null&&orientation.isNotEmpty:step==2?looking.isNotEmpty:step==3?photos>=2:desires.isNotEmpty&&bio.trim().isNotEmpty;
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(leading:step>0?IconButton(onPressed:()=>setState(()=>step--),icon:const Icon(Icons.arrow_back)):null,title:Text('3TRIO · '+(step+1).toString()+'/5')),body:Padding(padding:const EdgeInsets.all(22),child:Column(children:[LinearProgressIndicator(value:(step+1)/5,color:restoredPrimary),const SizedBox(height:24),Expanded(child:SingleChildScrollView(child:_body())),const SizedBox(height:14),SizedBox(width:double.infinity,height:54,child:FilledButton(onPressed:ok?()=>step<4?setState(()=>step++):Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const RestoredHome())):null,style:FilledButton.styleFrom(backgroundColor:restoredPrimary),child:Text(step==4?'Create Profile':'Continue')))])));
 Widget _body(){
  if(step==0)return _choices('I am a...',const ['Man','Woman','Non-binary','Couple'],gender,(x)=>setState(()=>gender=x));
  if(step==1)return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('A few extra details',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:20),TextField(onChanged:(v)=>name=v,decoration:const InputDecoration(labelText:'First name',border:OutlineInputBorder())),const SizedBox(height:14),TextField(onChanged:(v)=>age=v,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Age',border:OutlineInputBorder())),const SizedBox(height:18),const Text('Sexuality / orientation',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),Wrap(spacing:8,children:['Straight','Bi','Gay','Lesbian','Pansexual','Queer'].map((x)=>ChoiceChip(label:Text(x),selected:orientation==x,onSelected:(_)=>setState(()=>orientation=x))).toList())]);
  if(step==2)return _chips('What are you looking for?',lookingForOptions,looking,8);
  if(step==3)return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Your photos',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('At least 2 · maximum 5'),const SizedBox(height:20),GridView.count(crossAxisCount:3,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:10,mainAxisSpacing:10,children:List.generate(5,(i)=>InkWell(onTap:()async{final x=await ImagePicker().pickImage(source:ImageSource.gallery);if(x!=null&&photos<5)setState(()=>photos++);},child:Container(decoration:BoxDecoration(color:Colors.grey.shade200,borderRadius:BorderRadius.circular(16)),child:Icon(i<photos?Icons.check_circle:Icons.add_a_photo,color:i<photos?Colors.green:Colors.grey)))))]); 
  return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[_chips('Desires',desireOptions,desires,8),const SizedBox(height:20),const Text('Bio',style:TextStyle(fontWeight:FontWeight.bold,fontSize:18)),const SizedBox(height:8),TextField(maxLines:5,onChanged:(v)=>bio=v,decoration:const InputDecoration(hintText:'Tell people about you / us...',border:OutlineInputBorder()))]);
 }
 Widget _choices(String title,List<String> xs,String selected,ValueChanged<String> f)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:32,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Choose your profile type'),const SizedBox(height:22),...xs.map((x)=>Padding(padding:const EdgeInsets.only(bottom:12),child:SizedBox(width:double.infinity,height:62,child:OutlinedButton(onPressed:()=>f(x),style:OutlinedButton.styleFrom(side:BorderSide(color:selected==x?restoredPrimary:Colors.grey,width:selected==x?2:1),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(17))),child:Row(children:[Icon(selected==x?Icons.radio_button_checked:Icons.radio_button_off,color:selected==x?restoredPrimary:Colors.grey),const SizedBox(width:12),Text(x)]))))]);
 Widget _chips(String title,List<String> xs,Set<String> selected,int max)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:7),Text('Pick up to '+max.toString()),const SizedBox(height:18),Wrap(spacing:8,runSpacing:8,children:xs.map((x)=>FilterChip(label:Text(x),selected:selected.contains(x),onSelected:(v)=>setState((){if(v&&selected.length<max)selected.add(x);if(!v)selected.remove(x);}))).toList())]);
}

class RestoredHome extends StatefulWidget{const RestoredHome({super.key});@override State<RestoredHome>createState()=>_HomeState();}
class _HomeState extends State<RestoredHome>{int tab=0;@override Widget build(BuildContext c){final pages=<Widget>[const RestoredExplore(),const RestoredMatch(),const FeedScreen(),const RestoredMessages(),const MeScreen()];return Scaffold(body:IndexedStack(index:tab,children:pages),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[NavigationDestination(icon:Icon(Icons.explore),label:'Explore'),NavigationDestination(icon:Icon(Icons.favorite),label:'Match'),NavigationDestination(icon:Icon(Icons.dynamic_feed),label:'Feed'),NavigationDestination(icon:Icon(Icons.chat),label:'Chat'),NavigationDestination(icon:Icon(Icons.person),label:'Me')]));}}

class RestoredExplore extends StatefulWidget{const RestoredExplore({super.key});@override State<RestoredExplore>createState()=>_ExploreState();}
class _ExploreState extends State<RestoredExplore>{bool mapOn=true;int mode=0;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Explore'),actions:[Row(children:[const Text('Map'),Switch(value:mapOn,activeColor:restoredPrimary,onChanged:(v)=>setState(()=>mapOn=v))]),IconButton(onPressed:()=>showModalBottomSheet(context:c,builder:(_)=>const _Filters()),icon:const Icon(Icons.tune))]),body:Column(children:[Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:_Tab(text:'Map',on:mode==0,onTap:()=>setState(()=>mode=0))),const SizedBox(width:8),Expanded(child:_Tab(text:'City Search',on:mode==1,onTap:()=>setState(()=>mode=1)))])),if(mode==0&&mapOn)const Padding(padding:EdgeInsets.symmetric(horizontal:16,vertical:4),child:Row(children:[Text('12 people nearby',style:TextStyle(color:restoredPrimary,fontWeight:FontWeight.bold)),Spacer(),Text('Approx. locations',style:TextStyle(color:Colors.grey,fontSize:11))])),Expanded(child:mode==0&&mapOn?const RestoredMap():const RestoredCitySearch())]));}
class _Tab extends StatelessWidget{final String text;final bool on;final VoidCallback onTap;const _Tab({required this.text,required this.on,required this.onTap});@override Widget build(BuildContext c)=>InkWell(onTap:onTap,child:Container(alignment:Alignment.center,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:on?restoredPrimary:Colors.grey.shade200,borderRadius:BorderRadius.circular(24)),child:Text(text,style:TextStyle(color:on?Colors.white:Colors.grey,fontWeight:FontWeight.bold))));}
class _Filters extends StatelessWidget{const _Filters();@override Widget build(BuildContext c)=>SafeArea(child:Padding(padding:const EdgeInsets.all(22),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Filter Matches',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),const Text('Age Range 18 – 60'),RangeSlider(values:const RangeValues(18,60),min:18,max:80,onChanged:(_){ }),const Text('Maximum Distance 50 km'),Slider(value:50,min:5,max:100,onChanged:(_){ }),const SizedBox(height:10),const Text('Interests: Couples · Dating · Friends · Travel'),const SizedBox(height:16),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Apply Filters')))])));}

class RestoredCitySearch extends StatefulWidget{const RestoredCitySearch({super.key});@override State<RestoredCitySearch>createState()=>_CityState();}
class _CityState extends State<RestoredCitySearch>{String q='';@override Widget build(BuildContext c){final list=q.isEmpty?profiles:profiles.where((p)=>p.name.toLowerCase().contains(q.toLowerCase())||p.gender.toLowerCase().contains(q.toLowerCase())).toList();return Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,0,16,8),child:TextField(onChanged:(v)=>setState(()=>q=v),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Search city e.g. Faridabad, Noida, Delhi',border:OutlineInputBorder()))),Padding(padding:const EdgeInsets.symmetric(horizontal:16,vertical:4),child:Row(children:[Text(list.length.toString()+' results',style:const TextStyle(fontWeight:FontWeight.bold)),const Spacer(),const Text('City / area',style:TextStyle(color:Colors.grey,fontSize:12))])),Expanded(child:GridView.builder(padding:const EdgeInsets.all(12),itemCount:list.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:10,mainAxisSpacing:10,childAspectRatio:.68),itemBuilder:(_,i)=>_Grid(p:list[i]))) ]);}}
class _Grid extends StatelessWidget{final TrioProfile p;const _Grid({required this.p});@override Widget build(BuildContext c)=>GestureDetector(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>RestoredProfile(profile:p))),child:ClipRRect(borderRadius:BorderRadius.circular(18),child:Stack(fit:StackFit.expand,children:[Image.network(p.photo,fit:BoxFit.cover),const DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Colors.transparent,Colors.black87]))),Positioned(left:10,bottom:10,child:Text(p.name+'\n'+p.age+' · '+p.gender,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.bold)))])));}

class RestoredMap extends StatefulWidget{const RestoredMap({super.key});@override State<RestoredMap>createState()=>_MapState();}
class _MapState extends State<RestoredMap>{LatLng center=const LatLng(28.4089,77.3178);@override void initState(){super.initState();_locate();}Future<void>_locate()async{try{if(await Geolocator.isLocationServiceEnabled()){var p=await Geolocator.checkPermission();if(p==LocationPermission.denied)p=await Geolocator.requestPermission();if(p==LocationPermission.always||p==LocationPermission.whileInUse){final x=await Geolocator.getCurrentPosition();center=LatLng(x.latitude,x.longitude);if(mounted)setState((){});}}}catch(_){}}@override Widget build(BuildContext c){final o=[const LatLng(.006,.004),const LatLng(-.004,.007),const LatLng(.008,-.006),const LatLng(-.007,-.004)];return FlutterMap(options:MapOptions(initialCenter:center,initialZoom:11.8),children:[TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'com.aistudio.threetrio.jxhk'),MarkerLayer(markers:List.generate(profiles.length,(i)=>Marker(point:LatLng(center.latitude+o[i].latitude,center.longitude+o[i].longitude),width:100,height:90,child:GestureDetector(onTap:()=>showModalBottomSheet(context:c,builder:(_)=>_MapCard(p:profiles[i])),child:Column(children:[CircleAvatar(radius:27,backgroundImage:NetworkImage(profiles[i].photo)),Container(color:Colors.white,padding:const EdgeInsets.symmetric(horizontal:4,vertical:2),child:Text(profiles[i].name+' · '+(10+i*7).toString()+' km',style:const TextStyle(fontSize:9,fontWeight:FontWeight.bold)))])))))]);}}
class _MapCard extends StatelessWidget{final TrioProfile p;const _MapCard({required this.p});@override Widget build(BuildContext c)=>SafeArea(child:Padding(padding:const EdgeInsets.all(16),child:Column(mainAxisSize:MainAxisSize.min,children:[Row(children:[CircleAvatar(radius:30,backgroundImage:NetworkImage(p.photo)),const SizedBox(width:12),Expanded(child:Text(p.name+' · '+p.age+'\n'+p.gender,style:const TextStyle(fontSize:19,fontWeight:FontWeight.bold)))]),const SizedBox(height:10),Text(p.bio),const SizedBox(height:10),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>RestoredProfile(profile:p))),child:const Text('View Profile'))])));}

class RestoredMatch extends StatefulWidget{const RestoredMatch({super.key});@override State<RestoredMatch>createState()=>_MatchState2();}
class _MatchState2 extends State<RestoredMatch>{int i=0;double dx=0;final h=<int>[];void move(int d){final p=profiles[i];h.add(i);setState((){i=(i+1)%profiles.length;dx=0;});if(d>0)showDialog(context:context,builder:(_)=>AlertDialog(title:const Text("It's a Match! 💕"),content:CircleAvatar(radius:44,backgroundImage:NetworkImage(p.photo)),actions:[FilledButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>RestoredChat(profile:p))),child:const Text('Message')),TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Keep swiping'))]));}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Match')),body:GestureDetector(onHorizontalDragUpdate:(d)=>setState(()=>dx+=d.delta.dx),onHorizontalDragEnd:(_){if(dx.abs()>100)move(dx>0?1:-1);},child:Stack(alignment:Alignment.center,children:[_Swipe(p:profiles[i],dx:dx),Positioned(bottom:16,child:Row(children:[_A(icon:Icons.undo,color:Colors.orange,onTap:()=>h.isNotEmpty?setState(()=>i=h.removeLast()):null),_A(icon:Icons.close,color:Colors.red,onTap:()=>move(-1)),_A(icon:Icons.bolt,color:Colors.orange,onTap:()=>_message(c,'Ping','Ping this profile')), _A(icon:Icons.favorite,color:Colors.green,onTap:()=>move(1))]))]));}
class _Swipe extends StatelessWidget{final TrioProfile p;final double dx;const _Swipe({required this.p,required this.dx});@override Widget build(BuildContext c)=>Transform.translate(offset:Offset(dx*.2,0),child:Card(margin:const EdgeInsets.fromLTRB(14,18,14,90),clipBehavior:Clip.antiAlias,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(24)),child:Stack(fit:StackFit.expand,children:[Image.network(p.photo,fit:BoxFit.cover),const DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Colors.transparent,Colors.black87]))),Positioned(left:18,right:18,bottom:22,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p.name+', '+p.age,style:const TextStyle(color:Colors.white,fontSize:27,fontWeight:FontWeight.w900)),Text(p.gender+' · 10 km away',style:const TextStyle(color:Colors.white70)),Text(p.bio,style:const TextStyle(color:Colors.white)),const Text('✦ AI Top Match',style:TextStyle(color:Colors.amber,fontWeight:FontWeight.bold))]))])));}
class _A extends StatelessWidget{final IconData icon;final Color color;final VoidCallback onTap;const _A({required this.icon,required this.color,required this.onTap});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(horizontal:5),child:InkWell(onTap:onTap,child:Container(width:58,height:58,decoration:BoxDecoration(shape:BoxShape.circle,border:Border.all(color:Colors.grey)),child:Icon(icon,color:color))));}

class RestoredMessages extends StatelessWidget{const RestoredMessages({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Chat')),body:ListView(children:[const Padding(padding:EdgeInsets.fromLTRB(18,14,18,8),child:Text('Matches',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900))),SizedBox(height:105,child:ListView.separated(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:18),itemCount:profiles.length,separatorBuilder:(_,__)=>const SizedBox(width:12),itemBuilder:(_,i)=>GestureDetector(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>RestoredChat(profile:profiles[i]))),child:Column(children:[CircleAvatar(radius:32,backgroundImage:NetworkImage(profiles[i].photo)),Text(profiles[i].name,style:const TextStyle(fontSize:10,fontWeight:FontWeight.bold))])))),const Padding(padding:EdgeInsets.fromLTRB(18,8,18,8),child:Text('Chats',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900))),...profiles.map((p)=>ListTile(leading:CircleAvatar(backgroundImage:NetworkImage(p.photo)),title:Text(p.name),subtitle:const Text('Matched · Protected chat'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>RestoredChat(profile:p))))]));}
class RestoredChat extends StatefulWidget{final TrioProfile profile;const RestoredChat({super.key,required this.profile});@override State<RestoredChat>createState()=>_ChatState2();}
class _ChatState2 extends State<RestoredChat>{final ctl=TextEditingController();final msgs=<String>['Hey 👋','Hi, nice to meet you.'];@override void dispose(){ctl.dispose();super.dispose();}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.profile.name),actions:[IconButton(onPressed:()=>_message(c,'Audio call','Audio call opened.'),icon:const Icon(Icons.call)),IconButton(onPressed:()=>_message(c,'Video call','Video call opened.'),icon:const Icon(Icons.videocam))]),body:Column(children:[Expanded(child:ListView.builder(itemCount:msgs.length,itemBuilder:(_,i)=>Align(alignment:i.isOdd?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.all(7),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:i.isOdd?restoredPrimary:Colors.grey.shade200,borderRadius:BorderRadius.circular(17)),child:Text(msgs[i],style:TextStyle(color:i.isOdd?Colors.white:Colors.black)))))),SafeArea(child:Row(children:[Expanded(child:TextField(controller:ctl,decoration:const InputDecoration(hintText:'Message…'))),IconButton(onPressed:(){if(ctl.text.trim().isNotEmpty)setState((){msgs.add(ctl.text.trim());ctl.clear();});},icon:const Icon(Icons.send))]))]));}

class RestoredProfile extends StatefulWidget{final TrioProfile profile;const RestoredProfile({super.key,required this.profile});@override State<RestoredProfile>createState()=>_ProfileState();}
class _ProfileState extends State<RestoredProfile>{int page=0;@override Widget build(BuildContext c){final photos=<String>[widget.profile.photo,'https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=1000','https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=1000'];return Scaffold(appBar:AppBar(title:const Text('Profile')),body:Column(children:[SizedBox(height:430,child:Stack(children:[PageView.builder(scrollDirection:Axis.vertical,itemCount:photos.length,onPageChanged:(v)=>setState(()=>page=v),itemBuilder:(_,i)=>Image.network(photos[i],fit:BoxFit.cover,width:double.infinity)),Positioned(top:14,right:14,child:Container(color:Colors.black54,padding:const EdgeInsets.all(7),child:Text((page+1).toString()+'/'+photos.length.toString(),style:const TextStyle(color:Colors.white)))),Positioned(bottom:14,left:14,child:Text(widget.profile.name+', '+widget.profile.age+'\n'+widget.profile.gender+' · 10 km away',style:const TextStyle(color:Colors.white,fontSize:26,fontWeight:FontWeight.w900)))])),Expanded(child:ListView(padding:const EdgeInsets.all(18),children:[Text(widget.profile.name+', '+widget.profile.age,style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Wrap(spacing:7,children:widget.profile.interests.map((x)=>Chip(label:Text(x))).toList()),const SizedBox(height:12),_Card(title:'Desires / Looking for',child:Wrap(spacing:7,children:['Women','Men','Couples (FM)','Couples (FF)','Couples (MM)','25–45'].map((x)=>Chip(label:Text(x))).toList())),const SizedBox(height:12),_Card(title:'Basic Info',child:Column(children:[_row('Gender',widget.profile.gender),_row('Location','Delhi NCR'),_row('Distance','10 km away'),_row('Relationship status','Open to explore'),_row('Education','No answer')])),const SizedBox(height:12),_Card(title:'About Me / Us',child:Text(widget.profile.bio)),const SizedBox(height:18),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>Navigator.pop(c),child:const Text('Pass'))),const SizedBox(width:8),Expanded(child:FilledButton(onPressed:(){final uid=FirebaseAuth.instance.currentUser?.uid;if(uid!=null)FirestoreService().like(uid,widget.profile.name);_message(c,'Liked','Like sent.');},child:const Text('♥ Like')))])]))]));}}
Widget _row(String a,String b)=>Padding(padding:const EdgeInsets.symmetric(vertical:6),child:Row(children:[Expanded(child:Text(a,color:Colors.grey)),Expanded(child:Text(b,style:const TextStyle(fontWeight:FontWeight.bold)))]));
class _Card extends StatelessWidget{final String title;final Widget child;const _Card({required this.title,required this.child});@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:10),child])));}
void _message(BuildContext c,String title,String msg)=>showModalBottomSheet(context:c,builder:(_)=>SafeArea(child:Padding(padding:const EdgeInsets.all(22),child:Column(mainAxisSize:MainAxisSize.min,children:[Text(title,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:10),Text(msg),const SizedBox(height:18),FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('Close'))]))));
